### ISSUE TITLE
Support for new motion sensor

### ISSUE THREAD

**Issue by genfersee** [johannrichard/homebridge-mystrom#5]
Dear @johannrichard ,
Will you add support to the new myStrom motion sensor?
Kind regards!

**Comment by johannrichard** [comment]
It's not planned at the moment (as I don't own one). Right now, I'm looking into diving in a bit again, but can't commit yet.

**Comment by genfersee** [comment]
Thanks for answering! I managed to import my myStrom motion sensor in Homekit via homebridge-http-webhooks plugin.
